### ISSUE TITLE
add data compression 

### ISSUE THREAD

**Issue by bumi** [GreatLakesEnergy/sesh-api-helper#14]
because of running on limit 2G we need to make sure that we send as little data as possible. 
the requests needs to be fast and cheap.

**Comment by bumi** [comment]
wondering if default gzip is enough? which can be handled done by the web sever and we only would need to teach GZIP to the units.

**Comment by jlark** [comment]
We should start with GZIP on a minimum. This will happen on the RMC side clearly. Does anything need to happen on Kraken side?

**Comment by bumi** [comment]
If kraken is running behind a webserver like nginx that one should be able to handle the gzip compression and there is no need to do anything on the app side.

**Comment by jlark** [comment]
OK, I'm currently doing some productionization of things through ansible and I put kraken on gunicorn and nginx so that's done. I'll have to enable this on the RMC side as a TODO.

**Comment by jlark** [comment]
I've enabled gzip compression on the RMC and the difference is very significant. With a few tests with random data I saw the size of packets halved. With real data it was even more impressive.
- data size  before 999
- data size  after 226

Obviously as data is packaged up and sent in bulk the significance becomes compression becomes even better.. So I'm thinking I might collect data on the RMC and send them over perhaps every 10 minutes.

Though I'm having difficulty configuring NGINX to accept the compressed data. So far I've been getting 400 errors with no luck so far. Errors are not helpful at all. I'm tempted to simply add this to Kraken using zlib.

**Comment by jlark** [comment]
https://www.nginx.com/resources/admin-guide/compression-and-decompression/

**Comment by bumi** [comment]
fyi. just ran across this article: http://highscalability.com/blog/2016/3/21/to-compress-or-not-to-compress-that-was-ubers-question.html

**Comment by jlark** [comment]
So ditch Json continue with binary protocol and use zlib.

Makes sense. I think we test it too. We'll have some versions running json and some running binary. The thing is as the data type changes so does a lt of parameters. With our data there is a lot of repitition so compression does wonders.

Would be curios to compare it to binary.

**Comment by jlark** [comment]
Good article btw. Thanks for sharing!

**Comment by bumi** [comment]
we also have to consider CPU/memory power on the unit. I am happy that gzip is working there.

**Comment by jlark** [comment]
Exactly, everything has a cost.

**Comment by jlark** [comment]
I'm going to implement the option to use http://msgpack.org/index.html on the RMC side. Can you add this option to Kraken as well?

**Comment by bumi** [comment]
OK, will do. do you send `application/x-msgpack` as content type?

**Comment by jlark** [comment]
Sounds good.

**Comment by bumi** [comment]
oh and have you tested if the results are better with gzip + msgpack as in comparison to gzip + json?

**Comment by jlark** [comment]
No I haven't yet. Should get that tested soon.
