### ISSUE TITLE
authenticate/identify units

### ISSUE THREAD

**Issue by bumi** [GreatLakesEnergy/sesh-api-helper#15]
Mainly for monitoring reasons we want to identify the units that send data. 

current idea is to use a simple API token. 
We configure any unit + generate the key in the dashboard app, put the key on the unit and the api-helper can load the unit information on request from the dashboard database.

**Comment by jlark** [comment]
To give you some background. Each RMC image is currently built with Ansible. 
It will get the latest code from our repo's compile and configure everything straight on the RMC unit. 
Each unit needs to be identified and having a apikey is perhaps the best way.

We could have this auto-generated during build time of the RMC through Ansible.

**Comment by bumi** [comment]
ahh, that sounds pretty good. 
So during build time through ansible we should register the RMC at the dashboard - with required meta data (site, etc.). it gets the API key, stores it on the RMC and kraken can search in the DB on request using the API key.

**Comment by bumi** [comment]
the API key and the "unit" information will be stored in the `seshdash_sesh_site` table? 

(which also means we no longer will have a general global API key - was we currently do)

**Comment by jlark** [comment]
Yes so the RMC account is a simple table that's a foreign key in the `seshdash_sesh_site` table.
`seshdash_RMC_Account` is the table name.

**Comment by bumi** [comment]
included in #17

**Comment by bumi** [comment]
done
