### ISSUE TITLE
calculate traffic (incoming/outgoing)

### ISSUE THREAD

**Issue by bumi** [GreatLakesEnergy/sesh-api-helper#19]
In order to verify bandwidth charges we want to measure the traffic coming from every unit. That includes incoming and outgoing traffic. 
The data should be stored in a DB and probably get aggregated per billing cycle/month. 

To properly calculate incoming/outgoing traffic we will need to do that at least on nginx level.

**Comment by alptilev** [comment]
Getting the data from nginx is going to be challenging as http does have sigificant overhead. To start with though, looking at the content-length should give us a good enough data. _____________________________

**Comment by bumi** [comment]
but we would need that overhead because we are charged for that, no? just looking at the request body would be a too big difference, no?

**Comment by alptilev** [comment]
Its hard to say without looking at the data. Soninthink first stepmwould be looking at message body. One other option is measuring it on the network side on the rmc. This would give a much more complete picture.

On Mon, Apr 4, 2016 at 10:30 AM -0700, "Michael Bumann" notifications@github.com wrote:

but we would need that overhead because we are charged for that, no? just looking at the request body would be a too big difference, no?

---

**Comment by bumi** [comment]
does it make sense to use something like munin or some other monitoring tool to look at the traffic?

**Comment by jlark** [comment]
Could do that but also might be overkill. I eas simply thinkng of scraping ifconfg for tx and rx bytes data for the ppp interface. 

On Mon, Apr 4, 2016 at 12:39 PM -0700, "Michael Bumann" notifications@github.com wrote:

does it make sense to use something like munin or some other monitoring tool to look at the traffic?

**Comment by jlark** [comment]
Every 1.0s: ifconfig eth0                                               Tue Apr  5 08:59:50 2016
`$> watch -n 1 -d ifconfig eth0`

```
eth0      Link encap:Ethernet  HWaddr 00:0d:3a:23:57:0c
          inet addr:10.0.0.6  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::20d:3aff:fe23:570c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:674764 errors:0 dropped:0 overruns:0 frame:0
          TX packets:335994 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
     **     RX bytes:806924940 (806.9 MB)  TX bytes:146140008 (146.1 MB) **
```

**Comment by jlark** [comment]
Every 1.0s: ifconfig eth0                                               Tue Apr  5 08:59:50 2016
`$> watch -n 1 -d ifconfig eth0`

```
eth0      Link encap:Ethernet  HWaddr 00:0d:3a:23:57:0c
          inet addr:10.0.0.6  Bcast:10.0.0.255  Mask:255.255.255.0
          inet6 addr: fe80::20d:3aff:fe23:570c/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:674764 errors:0 dropped:0 overruns:0 frame:0
          TX packets:335994 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
     **     RX bytes:806924940 (806.9 MB)  TX bytes:146140008 (146.1 MB) **
```

**Comment by jlark** [comment]
Reviving this thread. I now have a script to calculate data usage on the PPP0 connection on the RMC.
I think it would be useful to send the data once a day.  Given that format of the data it could go straight to influx as well.
