### ISSUE TITLE
Sesh_RMC_Account table name is incorrect

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-api-helper#23]
In validate api_key.

Table name for the RMC accounts is hardcoded and incorrect. All tables have the prefix `seshdash`

Perhaps this could be added into the get_table function to append app_name to all tables before requested?

**Comment by bumi** [comment]
I will make the RMC_accounts table configurable. 
but do we really want to have everything configurable? 
The app is so special for our usecase and more configuration makes it harder to initially run it. 

also if we want to auto append a prefix, the prefix needs to be configurable. and imho the code would become less obvious... when `get_table('RMC_Account')` suddenly looks for a table called `seshdash_RMC_Account` - it only saves us a few letters but adds a quite some code.

**Comment by bumi** [comment]
btw. the table name (Sesh_RMC_Account) is from the ERD.
