### ISSUE TITLE
api not working in Gunicorn

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-api-helper#29]
see: https://rollbar.com/GLE/Sesh-API/items/9/

I think this is endemic to how the SQLAlchemy engine is created and how gunicorn runs the code.

`
if __name__ == "__main__":
    port = int(os.environ.get('FLASK_PORT', 3000))
    # Use 0.0.0.0 to make server visable externally
    host = os.environ.get('FLASK_HOST', '')
    app.engine = SQLAlchemy(app).engine
    app.run(host=host,port=port)
`
This will work fine in the command line however I think gunicorn is importing the python code hence this section isn't getting run.

**Comment by bumi** [comment]
I don't have access to rollbar. can you add me there?

**Comment by bumi** [comment]
probably I have too little knowledge/experience there. - sadly also I haven't seen many flask examples.

**Comment by jlark** [comment]
Sent you an invite a few days ago.
Nothing?

**Comment by bumi** [comment]
nope, no email and no access. Just double checked also the spam folder.

**Comment by jlark** [comment]
Ah it's a tricky one. will send a PR with fix.
