### ISSUE TITLE
Simple UI to see incoming data

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-api-helper#32]
A simple UI where the last incoming packet is dispalyed and timestamp showing when it arrived. For each site. This would be useful for debugging and general status checking.

**Comment by bumi** [comment]
ok, can do that. this is for us only, correct?
How should we do the authentication? 

regarding debugging... it might make sense to optimize logging and make the logs available through a searchable interface?

**Comment by jlark** [comment]
re:logging a some sort of log aggregator would be nice. Any recs on that?

I think BasicHTTP Auth is fine and admin creds can be defined in the config file.

**Comment by bumi** [comment]
self hosted: [graylog](https://www.graylog.org/)
hosted: [papertrail](https://papertrailapp.com/)

**Comment by bumi** [comment]
It might make sense to create a new flask app for the UI... so not put the UI code in api.py. 
This would clearly separate the concerns and not mix the API logic with a admin UI-logic.
For example: the API requires an API key and checks that in a `before_request` in the UI case we want to have some authentication (http basic auth maybe). To make this work in one app we would need to add checks and logic to check if it is a UI or API request. 

Also considering that this code base is already growing I think we should not throw more slightly related code at it. 

a new flask app can reuise the same configuration and obviously would connect to the same DB to display the data. 

what do you think?

**Comment by jlark** [comment]
I like the idea of seperating the UI code as it would help keep the logic clear, like you said. 
My only concerns around operation. So here are a few questions and requirements. @rawjazz has already started working on this but he's also facing the same questions.
- The admin UI should run automatically when the API is run. Would prefer not running a seperate gunicorn process for it. (Create another service,  etc)
- How will it get the data from the API. I'de prefer it not reading from a database. (I'd prefer not to store this data in a table).  Perhaps there is a seperate log file which it reads from? One for succesfull transactions another one for failed. One file for stats maybe.  My thoughts here is this data is ephemeral and is only useful for a short time.

Maybe the answer is simply using a logging tool, like graylog? (but setting up external services also comes at a cost as they can be over complicated sometimes.)

**Comment by jlark** [comment]
http://flask.pocoo.org/docs/0.10/patterns/appdispatch/ 

I think this could be a way to handle both running behind the same WSGI

**Comment by bumi** [comment]
1) this should be possible. at least it is in the ruby/rack world and WSGI is similar if I understand that correctly. 
2) which data are you talking about? why should the UI not connect to the DB (as the API is doing?)

in general I'd be all for a centralized logging tool (additionally - depends on what you want to achieve with the UI) which allows us to follow what is going on in the whole network. Have you looked at graylog or papertrail? the setup should be pretty easy as all are supporting syslog.

**Comment by bumi** [comment]
ahh ja, appdispatch seems to be what we'd be looking for.

**Comment by jlark** [comment]
I think I'll be definitly looking at centralized logging this week. I think it's a definite need and total PITA currently to debug prod. So I'll let you know the status of that.

With respect to data for the admin UI. I want it do be super light weight so it's only showing success failures and very basic counters and not all of that is stored in the database. IE. failed requests are thrown away and I'd like to see them in the admin UI for debugging. (Why are they failing etc.)

So I was thinking of a simpler ephemeral use of data that's in memory and perhaps simply the last 100 request or 24 hours type.

**Comment by bumi** [comment]
but shouldn't failed requests be in the exception tracking tool? 
also for seeing requests I really believe a logging tool is a good solution. especially with powerful search possibilities.

**Comment by jlark** [comment]
well yes and no. There will be requests that are dropped that will not cause an exception(wrong key, empty body, etc) Also I want to see simple stats like the number of request in last hour , number which failed, succeeded. So simple counters.

**Comment by bumi** [comment]
which can be in the log tool.
if we drop requests due to an invalid API key for example we write a log
entry. this data ends up in the logging tool and can be searched and
processed there
I think graylog has nicer graphs by default, but we will see that after
testing the tools.

On Monday, May 16, 2016, Alp Tilev notifications@github.com wrote:

> well yes and no. There will be requests that are dropped that will not
> cause an exception(wrong key, empty body, etc) Also I want to see simple
> stats like the number of request in last hour , number which failed,
> succeeded. So simple counters.
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/GreatLakesEnergy/sesh-api-helper/issues/32#issuecomment-219430786

## 

Michael Bumann

F       +49 (0) 176 22747893
E       hello@michaelbumann.com
T       twitter.com/bumi

**Comment by jlark** [comment]
OK I'm convinced. I like graylog but it's seems to want a lot of hardware since it's running Elasticsearch etc. So I think I'd have to put a seperate VPS for that which I'm not thrilled about. Should we go with papertrail instead?

**Comment by bumi** [comment]
yep,  let's use papertrail to see if it helps.
and if we like it it should be easy to switch.

(for a lot of (historical) data papertrail becomes expensive.)

On Monday, May 16, 2016, Alp Tilev notifications@github.com wrote:

> OK I'm convinced. I like graylog but it's seems to want a lot of hardware
> since it's running Elasticsearch etc. So I think I'd have to put a seperate
> VPS for that which I'm not thrilled about. Should we go with papertrail
> instead?
> 
> —
> You are receiving this because you were assigned.
> Reply to this email directly or view it on GitHub
> https://github.com/GreatLakesEnergy/sesh-api-helper/issues/32#issuecomment-219433579

## 

Michael Bumann

F       +49 (0) 176 22747893
E       hello@michaelbumann.com
T       twitter.com/bumi

**Comment by jlark** [comment]
Yes, I think papertrail get's expensive so graylog would be the longer term solution, but I prefer simplicity right now. Whichever is faster.
