### ISSUE TITLE
bulk import mapping from db

### ISSUE THREAD

**Issue by jlark** [GreatLakesEnergy/sesh-api-helper#37]
Hi Bumi,
So the final piece of the puzzle will be to get the bulk import mapping for each site straight from the dashboard db. 

So the goal would be to get all the sensors for a site and get the field they should be mapped to.
The sensors models start with a prefix 'sensor_'
https://github.com/GreatLakesEnergy/sesh-dash-beta/blob/master/seshdash/models.py

So basically to sum it up. Pull the mapping from the database rather than the config file.

**Comment by bumi** [comment]
Where are the fields stored? is that an attribute on the Sensor_\* models?

**Comment by jlark** [comment]
The fields names are stored in the dashboard DB.

https://gist.github.com/jlark/378aea80b44676ccc1aba5aa30ac27ad

**Comment by bumi** [comment]
hmmm. we somehow need something like: `node_id: { index: column }` to map the incoming request data to the the table columns. 
where would I find that information?

**Comment by jlark** [comment]
So we can currently get the Site_id based on the api_key ( by doing a reverse lookup in the RMC api table) I'm assuming we can also go a SQL query that says give me all the sensors that refernce this site.

from there we can get the `node_id`.  The index is defined by the field name (it currently is **not**, I'll change this)
then the column is the value of the field.

**Comment by bumi** [comment]
I do not understand the last part: "The index is defined by the field name" 
the index is an integer value - the array index of the data in the incoming request.
the field name/table name is a string. 
right now we have this mapping ( index => tablename ) so that we are able to gather the value from the incoming request and save it to the correct field. 

example of a request would be: 
`
[[121234123,9,16,1137],[2341234,11,17,1437]]
`

**Comment by bumi** [comment]
what is stored in the sensor tables?

**Comment by jlark** [comment]
Ah ok, let me try to elaborate. It might be easier to go over the example you provided. Let's this is request coming from site X, and it contains data from node:9  (node is defined by the index 1, index 0 is timestamp)

`[[121234123,9,16,1137]]`

let's assume site X has the following sensors ( 1 -  EmonTH )

```
class Sensor_EmonTx(models.Model):
     """        
     Table representative for the emon tx
     """
     NODE_ID_CHOICES = (
                         (20, 20),
                         (21, 21),
                         (22, 22),
                     )

     site = models.ForeignKey(Sesh_Site)
     node_id = models.IntegerField(default=0, choices=NODE_ID_CHOICES)
     index1= models.CharField(max_length=40, default="ac_power1")
     index2 = models.CharField(max_length=40, default="pv_production")
     index3 = models.CharField(max_length=40, default="consumption")
     index4 = models.CharField(max_length=40, default="grid_in")
     index5 = models.CharField(max_length=40, default="AC_Voltage_out")
     index6 = models.CharField(max_length=40, blank=True, null=True)
     index7 = models.CharField(max_length=40, blank=True, null=True)
     index8 = models.CharField(max_length=40, blank=True, null=True)
     index9 = models.CharField(max_length=40, blank=True, null=True)
     index10 = models.CharField(max_length=40, blank=True, null=True)
     index11 = models.CharField(max_length=40, blank=True, null=True)
     index12 = models.CharField(max_length=40, blank=True, null=True)

     def __str__(self):
         return "Emon tx sensor for " + self.site.site_name
```

so the API would say to the DB - Give me all the sensors belonging to site X with node_id=9
single object. the Column name in the model returned would be the index and the value in that would be the mapping name for that data.
Eg: 
`[[121234123,9,16,1137]]`
would become  based on the default values  [[121234123,9,16,1137]] 
`{timestamp: 121234123, node_id: 9,  ac_power1: 16,  pv_production:16,  consumption, 1137}`

and the sent to influx with. (each column is  a measurement name in influx.)

**Comment by jlark** [comment]
Ah ok, let me try to elaborate. It might be easier to go over the example you provided. Let's this is request coming from site X, and it contains data from node:9  (node is defined by the index 1, index 0 is timestamp)

`[[121234123,9,16,1137]]`

let's assume site X has the following sensors ( 1 -  EmonTH )

```
class Sensor_EmonTx(models.Model):
     """        
     Table representative for the emon tx
     """
     NODE_ID_CHOICES = (
                         (20, 20),
                         (21, 21),
                         (22, 22),
                     )

     site = models.ForeignKey(Sesh_Site)
     node_id = models.IntegerField(default=0, choices=NODE_ID_CHOICES)
     index1= models.CharField(max_length=40, default="ac_power1")
     index2 = models.CharField(max_length=40, default="pv_production")
     index3 = models.CharField(max_length=40, default="consumption")
     index4 = models.CharField(max_length=40, default="grid_in")
     index5 = models.CharField(max_length=40, default="AC_Voltage_out")
     index6 = models.CharField(max_length=40, blank=True, null=True)
     index7 = models.CharField(max_length=40, blank=True, null=True)
     index8 = models.CharField(max_length=40, blank=True, null=True)
     index9 = models.CharField(max_length=40, blank=True, null=True)
     index10 = models.CharField(max_length=40, blank=True, null=True)
     index11 = models.CharField(max_length=40, blank=True, null=True)
     index12 = models.CharField(max_length=40, blank=True, null=True)

     def __str__(self):
         return "Emon tx sensor for " + self.site.site_name
```

so the API would say to the DB - Give me all the sensors belonging to site X with node_id=9
single object. the Column name in the model returned would be the index and the value in that would be the mapping name for that data.
Eg: 
`[[121234123,9,16,1137]]`
would become  based on the default values  [[121234123,9,16,1137]] 
`{timestamp: 121234123, node_id: 9,  ac_power1: 16,  pv_production:16,  consumption, 1137}`

and the sent to influx with. (each column is  a measurement name in influx.)

**Comment by bumi** [comment]
ok so we iterate over the array values [2..-1] check if the table has a column named `index{n}` if so the value is the mapping name? 
sounds good. 

how do I know which sensor a site has? (Sensor_EmonTh, Sensor_EmonTx, etc.) - which are different tables.

**Comment by jlark** [comment]
Yes, exactly. 

I think the simples way would be to get the sensor tables (could query schema table) and within each sensor table query for sensors where  site_id=x (or we could put the sensor tables in the config)

**Comment by bumi** [comment]
ok, if the fields are only for the mapping? 
((( we could also store it in a column as json for example. (we are on mysql right, on pg we could use: https://www.postgresql.org/docs/9.0/static/hstore.html ) )))

**Comment by jlark** [comment]
yeah we could do that. I've thought about using things like delimiters within the field to store multiple values like arrays or pointers but I've tried to avoid this (it just felt too hacky, though I can't say the other solution isn't). The postgres solution is exactly what I've been looking for and unfortunately MYSQL AFAIK doesn't have such functions.
